SELECT * FROM DBA_PROFILES WHERE RESOURCE_NAME LIKE 'PASSWORD_LIFE_TIME';

SET SERVEROUTPUT ON;
DECLARE 
    DBMS_OUTPUT.PUT_LINE('ALTER PROFILE UNLIMITED LIFE PASSWORD');
    EXECUTE IMMEDIATE 'ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED';
    COMMIT;    
END 

SELECT * FROM DBA_PROFILES WHERE RESOURCE_NAME LIKE 'PASSWORD_LIFE_TIME';
