SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME like 'hr%';

SET SERVEROUTPUT ON;
DECLARE 
    DBMS_OUTPUT.PUT_LINE('ALTER PROFILE UNLIMITED LIFE PASSWORD');
    EXECUTE IMMEDIATE 'ALTER USER HR IDENTIFIED BY HR ACCOUNT UNLOCK';
    COMMIT;    
END 

SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME like 'hr%';